### ISSUE TITLE
handle client request

### ISSUE THREAD

**Issue by gkiko** [freeuni-sdp/xo-webui#1]
[ამ](https://github.com/freeuni-sdp/xo-main/wiki/Requirements#მიღწევები-და-ისტორია) მოთხოვნის მიხედვით მომხმარებელი შემოვა გვერდზე **webui.com/history** და ნახავს თავისი თამაშების ისტორიას. **webui.com/history/{game_id}** ლინკზე ნახავს კონკრეტული თამაშის მსვლელობას.

მეორე ლინკმა რომ იმუშაოს, ჩემი სერვისის გავლით უნდა მივმართო "ისტორიის" სერვისს. ამოვიღებ გადმოცემულ **game_id**-ის, წამოვიღებ შესაბამის `json`-ს ისტორიის სერვისისგან და დავუბრუნებ მომხმარებელს.

მეორე გზაა, webui მხოლოდ html/js/css-ებს აძლევდეს მომხმარებელს. ოღონდ ამ შემთხვევაში **webui.com/history/{game_id}** აღარ იმუშავებს. მომხმარებელს მოუწევს ჯერ სიის წამოღება და შემდეგ თამაშის არჩევა. კონკრეტული თამაშის ისტორიის მოთხოვნას კი ბრაუზერი გააკეთებს.

გვინდა აღწერილი ფუნქციონალი?

**Comment by gkiko** [comment]
მგონი პირველი ვარიანტია სწორი. მეორე ვარიანტის იმპელემტაციისას `origin is not allowed by Access-Control-Allow-Origin` შეცდომა ვარდება უსაფრთხოების დარღვევის გამო.

**Comment by gmamaladze** [comment]
არ ვარ დარწმუნებული რომ კარგად გავიგე რას გულისხმობ, მაგრამ პირველი ვარიანტს ვიტყოდი მეც. შეკითხვა თუ კვლავ აქტუალურია დააზუსტე. კოდი ან ფსევდოკიდიც დამეხმარებოდა.

**Comment by gkiko** [comment]
ბრაუზერი json-ების წამოსაღებად ჩემი სერვისის გავლით თუ პირდაპირ უნდა მიმართავდეს უკანა სერვისებს?

**Comment by gmamaladze** [comment]
პირდაპირ
